* [[file:20200916.html][Sep 16, 2020]]
The libressl "revert" was reverted. System update will replace libressl
dependencies with bearssl. You may choose to keep or remove bearssl after the
update.
* [[file:20200903.html][Sep 03, 2020]]
The default TLS provider has been reverted to =libressl=. System update will
replace bearssl dependencies with libressl. You may choose to keep or remove
bearssl after the update.
* [[file:20200727.html][Jul 27, 2020]]
Carbs Linux's fork of the =kiss= package manager has been renamed to =Carbs
  Packaging Tools= due to huge amount of changes. Your latest =kiss= update will
handle the bootstrapping. You will need to rename your =KISS-*= variables to
=CPT-*=.
* [[file:20200617.html][Jun 17, 2020]]
A new rootfs tarball including the changes to the core is released and can be
found on the downloads page.
* [[file:20200526.html][May 26, 2020]]
An initial version for binary package management is released. It can be found on
the [[https://github.com/CarbsLinux/kiss-bin][GitHub page]].
