#+TITLE: Roadmap for Carbs
#+AUTHOR: Cem Keylan
#+DATE: <2020-04-06 Mon>

It has been a busy week. There are lots of changes in direction, and more to
come. I want to talk a little about all of them.

** Carbs Linux Server Going Down

It became harder to maintain and pay for the server, and I will be shutting it
down in May. I am currently in the phase of carrying over everything to [[https://github.com/CarbsLinux][Github]].
The repository and the website is served on Github now. I have also moved the
[[https://github.com/CarbsLinux/wiki/wiki][Wiki]] to Github and anyone can edit it there. There are some outdated posts that
I will be fixing around this week.

I am not quite sure where to store the downloads page now. But I will be
switching that to a new source as well. (Maybe SourceHut?)

I feel a little sad for switching, but serving on Github is faster, cheaper, and
hassle-free.

** Forking KISS

I had a personal fork of KISS, which I enjoyed thoroughly. I didn't intend to
make it the default when I started it, but it has matured enough to be so. The
package manager can now be found on [[https://github.com/CarbsLinux/kiss][this repository]]. See it for the added
changes.

This will be a change for the better, as I can develop the package manager as it
fits my views.

** Small Changes on the Website

I have made some small changes on the website. The build is not dependent on
Plan9 utilities anymore. It was fun messing around with =rc= and =mk=, but they
are quite limited compared to POSIX shell.

RSS feeds are finally working as intended, both for the [[https://carbslinux.org/news.xml][news]] section, and the
[[https://carbslinux.org/rss.xml][blog]] section.

You can see every page's =.txt= output at the end of the page by clicking 'View
Page Source'. Meanwhile, I will be updating some pages to be a little more
'human-readable'.

** Outsources Repository

I have opened an =outsource= repository, which I will be pushing this week. I
will add a new post when I am ready to push it. I think it will be interesting,
it will also make more sense about the changes I have added to the package
manager. The now empty repository, can be found [[https://github.com/CarbsLinux/outsource][here]]!

** New Tarball

Finally, I have released a new tarball today, which can be obtained from the
[[https://dl.carbslinux.org/releases][downloads page]].

I am planning to add more of these update posts as I'm feeling better about the
website structure overall.
