#+TITLE: Carbs Linux
#+DESCRIPTION: a simple Linux distribution
#+OPTIONS: title:nil

Carbs Linux is a source-based Linux\reg distribution that aims to be simple,
flexible and extensible while staying as pragmatic and practical as possible.
The system can consist of as much or as little as its user can intend to.

* Package Manager
:PROPERTIES:
:CUSTOM_ID: package-manager
:END:

Carbs Linux uses its own package manager [[https://git.sr.ht/~carbslinux/cpt][Carbs Packaging Tools]], a POSIX shell
package manager forked from [[https://github.com/kisslinux/kiss][KISS]] with the tool-based approach of [[https://github.com/void-linux/xbps][xbps]]. Its aim
is to deliver easy-to-use tools while also providing a powerful POSIX shell
library that can be used to further extend and script the packaging system.


* Small base
:PROPERTIES:
:CUSTOM_ID: small-base
:END:

By default, Carbs Linux comes with busybox for coreutils, bearssl for its
crypto library, musl libc, and other basic utilities that are required for
building new software. The majority of the base packages are statically linked.


* Multiple Init Support
:PROPERTIES:
:CUSTOM_ID: multiple-init-support
:END:

Carbs Linux has support for multiple init systems and service supervisors. In
the main repository are

- [[carbs-pkg:core/sinit][sinit]] / [[carbs-pkg:extra/shinit][shinit]]
- [[carbs-pkg:core/busybox][busybox-init]] (SysVinit clone)
- [[carbs-pkg:core/runit][runit-init]]

for init systems, and

- [[carbs-pkg:core/sysmgr][sysmgr]]
- [[carbs-pkg:core/busybox][busybox-runit]]
- [[carbs-pkg:core/runit][runit]]

for service supervisors. The [[carbs-pkg:core/carbs-init][carbs-init]] package is the collection of init
scripts that ensure the interoperability of these init and service systems, and
make it easier for the user to switch to their preferred combinations of system
supervision.

Nothing holds you back, however, from ditching any of these and packaging some
other system supervision technique along with your own init scripts.


* Links
:PROPERTIES:
:CUSTOM_ID: links
:END:

- IRC - =#carbslinux= on freenode
- Reddit - [[https://reddit.com/r/carbslinux][r/carbslinux]]
- [[file:mailing-lists.org][Mailing Lists]]

* News
:PROPERTIES:
:CUSTOM_ID: news
:END:

[[file:./news.xml][RSS Feed]] | [[file:./news][See all news]]

#+INCLUDE: ../news/latest-news.org :minlevel 2
